services:
  web:
    build: .
    depends_on:
      - api
    ports:
      - "5173:80" # map host 5173 -> container 80 (so same port as vite dev if desired)
      - "80:80"   # also expose container port 80 on host port 80 for direct access via host IP
    restart: unless-stopped
    # Optional: mount local data for live editing of public/data
    volumes:
      - ./public/data:/usr/share/nginx/html/data:ro
      - ./nginx/ssl/server.crt:/etc/nginx/ssl/server.crt:ro
      - ./nginx/ssl/server.key:/etc/nginx/ssl/server.key:ro
      - ./nginx/default.conf:/etc/nginx/default.conf:ro
    networks:
      - app-network
  

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8787:8787"
    restart: unless-stopped
    volumes:
      - ./api/label_data.json:/app/label_data.json
    networks:
      - app-network

networks:
  app-network:
    driver: bridge